#!/bin/bash

set -eu

# Set up buildevents vars
export BUILD_START=$(date +%s)

#Fetch Buildevents
curl -L -o buildevents https://github.com/honeycombio/buildevents/releases/latest/download/buildevents-linux-amd64
chmod 755 buildevents